# -*- coding: utf-8 -*-
"""Problem12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uACpshSyDi6pvhW6ioofUo126WuwJIxF

Regression: Simple Linear
Dataset: advertising.csv
Apply Data pre-processing (Label Encoding , Data Transformation....)
techniques if necessary.
Explore whether TV advertising spending can predict the number of sales for
the product. Also display the regression results and plot the
regression line.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

df = pd.read_csv('/content/advertising.csv')
df.head()

df.isna().sum().sum()

df.shape

X = df[['TV']]
Y = df['Sales']

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

lr = LinearRegression()

lr.fit(x_train, y_train)
lr.score(x_train, y_train)

y_pred = lr.predict(x_test)
lr.score(x_test, y_test)

plt.scatter(x_test, y_test, color="red")
plt.plot(x_test, y_pred )
plt.show()

from sklearn import metrics
mse = metrics.mean_squared_error(y_test, y_pred)
mse

